language: python

python:
- '2.7'
- '3.5'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev

before_install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt

install:
- pip install -e .

script:
- nosetests -v -s
